# Generated by Django 5.2.16 on 2026-08-01 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('pdf', 'PDF'), ('url', 'Website URL'), ('text', 'Plain Text'), ('faq', 'FAQ')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, help_text='Text / FAQ content or crawled page text')),
                ('source_url', models.URLField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='knowledge/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('faiss_doc_id', models.CharField(blank=True, max_length=64)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_sources', to='employees.aiemployee')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
