# Generated by Django 5.2.17 on 2026-10-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgesource',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Publish this material in the website widget Articles & Search tabs.', verbose_name='Show as help article'),
        ),
    ]
