# Generated by Django 5.2.17 on 2026-10-04 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_otp_attempts'),
        ('workspaces', '0006_workspace_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='active_workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workspaces.workspace'),
        ),
    ]
