# Generated by Django 5.2.16 on 2026-08-01 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('sales_agent', 'Sales Agent'), ('support_specialist', 'Support Specialist'), ('booking_assistant', 'Booking Assistant'), ('lead_gen', 'Lead Gen')], default='support_specialist', max_length=40)),
                ('personality', models.CharField(choices=[('friendly', 'Friendly'), ('professional', 'Professional'), ('casual', 'Casual'), ('enthusiastic', 'Enthusiastic')], default='friendly', max_length=40)),
                ('language', models.CharField(default='en', max_length=20)),
                ('greeting_message', models.TextField(default='Hi! How can I help you today?')),
                ('system_prompt', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('brand_color', models.CharField(blank=True, max_length=7)),
                ('widget_token', models.CharField(editable=False, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'AI Employee',
                'verbose_name_plural': 'AI Employees',
                'ordering': ('-created_at',),
            },
        ),
    ]
