# Generated by Django 5.2.17 on 2026-09-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_aiemployee_capabilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiemployee',
            name='greeting_message',
            field=models.TextField(blank=True, help_text='Leave blank to use the default greeting for the chosen personality.'),
        ),
    ]
