# Generated by Django 5.2.16 on 2026-08-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_webhook_stripe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='widget_token',
            field=models.CharField(editable=False, max_length=64, unique=True),
        ),
    ]
