# Generated by Django 5.2.17 on 2026-09-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_workspace_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='away_message',
            field=models.TextField(blank=True, help_text='Shown in the widget outside office hours'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='office_hours',
            field=models.JSONField(blank=True, default=dict, help_text='{"mon": [["09:00", "18:00"]], ...}. Empty means the team is always reachable.'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='offline_form_enabled',
            field=models.BooleanField(default=True, help_text='Ask offline visitors to leave their details'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='timezone',
            field=models.CharField(default='UTC', help_text='IANA timezone the office hours below are expressed in, e.g. Asia/Kolkata', max_length=64),
        ),
    ]
