# Generated by Django 5.x

from django.db import migrations, models
import django.db.models.deletion
import django.conf


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_visitorprofile_employeetask'),
        migrations.swappable_dependency(django.conf.settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='taken_over_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='taken_over_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taken_over_sessions', to=django.conf.settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('human', 'Human takeover'), ('paused', 'Paused'), ('closed', 'Closed')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to=django.conf.settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('visitor', 'Visitor'), ('employee', 'AI Employee'), ('human', 'Team member'), ('system', 'System')], max_length=20),
        ),
        migrations.AddField(
            model_name='employeetask',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeetask',
            name='task_type',
            field=models.CharField(choices=[('qualify', 'Qualify visitor'), ('handoff', 'Team handoff'), ('schedule', 'Schedule / visit'), ('follow_up', 'Follow up'), ('contact', 'Contact collected')], max_length=20),
        ),
    ]
