# Generated by Django 5.2.17 on 2026-10-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_human_takeover'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='is_test',
            field=models.BooleanField(db_index=True, default=False, help_text='Playground / dashboard preview session — excluded from quota and analytics.'),
        ),
    ]
