# Generated by Django 5.2.17 on 2026-09-22 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_human_takeover'),
        ('employees', '0002_aiemployee_capabilities'),
        ('workspaces', '0006_workspace_away_message_workspace_office_hours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Teammate who owns this conversation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='first_human_response_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='first_response_at',
            field=models.DateTimeField(blank=True, help_text='When the first reply (AI or teammate) went out', null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='first_response_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='first_visitor_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='resolution_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='mentions',
            field=models.ManyToManyField(blank=True, help_text='Teammates @mentioned in a private note', related_name='mentioned_in_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('human', 'Human takeover'), ('paused', 'Paused'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('visitor', 'Visitor'), ('employee', 'AI Employee'), ('human', 'Team member'), ('system', 'System'), ('note', 'Private note')], max_length=20),
        ),
        migrations.CreateModel(
            name='ConversationRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(help_text='1 (bad) to 5 (great)')),
                ('comment', models.TextField(blank=True)),
                ('rated_human', models.BooleanField(default=False, help_text='True when a teammate had replied in this conversation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='employees.aiemployee')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='chat.chatsession')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='workspaces.workspace')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ConversationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('slug', models.SlugField()),
                ('color', models.CharField(default='#6366F1', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_tags', to='workspaces.workspace')),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('workspace', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='chatsession',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='chat.conversationtag'),
        ),
        migrations.CreateModel(
            name='CannedResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortcut', models.CharField(help_text='Typed as !shortcut in the reply box', max_length=40)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('uses', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canned_responses', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canned_responses', to='workspaces.workspace')),
            ],
            options={
                'ordering': ('shortcut',),
                'unique_together': {('workspace', 'shortcut')},
            },
        ),
    ]
